<?php

namespace SiteBundle\Repository;

/**
 * CommentPreferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentPreferenceRepository extends \Doctrine\ORM\EntityRepository
{

}
