<?php

namespace SiteBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

	public function findByUserid($id){
		//order by the most recent comment
		return $this->createQueryBuilder('comment')
	    ->select('comment')
	    ->orderBy('comment.id','DESC')
		->where('comment.user='.$id)
		->getQuery()
		->getResult();
	}
}
