<?php

namespace SiteBundle\Repository;

/**
 * MainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainRepository extends \Doctrine\ORM\EntityRepository
{
	// public function recentComments(){

	// 	//order by the most recent comments
	// 	return $this->createQueryBuilder('comment')
	// 	->orderBy('comment.date', 'DESC')
	//        ->setFirstResult(0)
	//        ->setMaxResults(5)		
	// 	->getQuery()
	// 	->getResult();
	// }
}
