<?php

namespace SiteBundle\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{
	public function searchMethod($term){

    $query = $this->createQueryBuilder('person')
        ->select('person')
        ->orderBy('person.lastname','ASC')
        ->andWhere('person.lastname LIKE :term')
        ->orWhere('person.firstname LIKE :term')
        ->orWhere('person.character LIKE :term')
        ->andWhere('person.validated = true')
        ->setParameter(':term','%'.$term.'%')
        ->getQuery();
    return $query->getResult();
    }
}
