<?php

namespace SiteBundle\Repository;

/**
 * SeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesRepository extends \Doctrine\ORM\EntityRepository
{
		public function showDetails($id){
		//order by the most recent articles
		return $this->createQueryBuilder('series')
		->where('series.id='.$id)
		->leftJoin('series.comments', 'com')
		// ->leftJoin('art.categories', 'cat')
		// ->leftJoin('art.image', 'img')
		->getQuery()
		->getSingleResult();
	}
}
