<?php

namespace SiteBundle\Repository;

/**
 * SeriesRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
