<?php

namespace SiteBundle\Repository;

/**
 * SeriesRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesRatingRepository extends \Doctrine\ORM\EntityRepository
{
	public function avgRatings($id){
		//average of the series
		return $this->createQueryBuilder('series_rating')
		->select("avg(series_rating.ratings) as average")
		->where('series_rating.series= :id')
		->setParameter('id', $id)
		->getQuery()
		->getSingleScalarResult();
	}

}
