<?php
namespace SiteBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function searchMethod($term){
        $query = $this->createQueryBuilder('user')
            ->select('user')
            ->orderBy('user.username','ASC')
            ->Where('user.username LIKE :term')
            ->setParameter(':term','%'.$term.'%')
            //->setMaxResults($limit)
            ->getQuery();
        return $query->getResult();
    }

    //autocomplete for message recipient
    public function listeUser($term)
    {
        $qb = $this->createQueryBuilder('u');
        $qb ->select('u.username')
            ->where('u.username LIKE :term')
            ->setParameter('term', '%'.$term.'%');
        $arrayAss= $qb->getQuery()
                   ->getArrayResult();
        //Transformer le tableau associatif en un tableau standard
        $array = array();
        foreach($arrayAss as $data)
        {
            $array[] = $data['username'];
        }
        return $array;
    }
}
