<?php
namespace SiteBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function searchMethod($term){
        //var_dump($term); die;
        $query = $this->createQueryBuilder('user')
            ->select('user')
            ->orderBy('user.username','ASC')
            ->Where('user.username LIKE :term')
            ->setParameter(':term','%'.$term.'%')
            //->setMaxResults($limit)
            ->getQuery();
        return $query->getResult();
    }
}
